services:
#    app_front_end.example:
#        class: App\FrontEndBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    site_bundle.service:
              class:  App\FrontEndBundle\Service\Srv
              arguments:
                  - @service_container