Bundles\StoreBundle\Entity\Page:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: text
    lifecycleCallbacks: {  }
